import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Footer, Header } from "./components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex flex-col items-center text-black justify-between h-screen bg-gradient-to-r from-bg-gradient-from from-0% to-bg-gradient-to to-150% bg-gradient-to-b">
          <div className="w-full overflow-y-scroll">
            <Header />
            {children}
          </div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
